# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-VKtO_37dt_3OpSbc55nh68pPqjKbt0g
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread(image.png)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.imshow(image_rgb)
plt.title(" image title")
plt.show()

blue_lower = np.array([100, 0, 0])
blue_upper = np.array([100, 255, 100])

green_lower = np.array([0, 100, 0])
green_upper = np.array([100, 255, 100])

blue_mask = cv2.inRange(image_rgb, blue_lower, blue_upper)
green_mask = cv2.inRange(image_rgb, green_lower, green_upper)

blue_area = cv2.countNonZero(blue_mask)
green_area = cv2.countNonZero(green_mask)

ratio = blue_area / (blue_area + green_area)

print("Nuclie:", blue_area)
print("Cytoplasm:", green_area)
print("Ratio:", ratio)